# Generated by Django 3.2.16 on 2023-12-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=16, verbose_name='Название')),
                ('code', models.CharField(default='Без кода', max_length=8, verbose_name='Код страны')),
                ('flag_url', models.CharField(default='Без флага', max_length=64, verbose_name='Ссылка на флаг страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=64, verbose_name='Название')),
                ('logo_url', models.CharField(default='Без логотипа', max_length=64, verbose_name='Ссылка на логотип лиги')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='Год сезона')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без имени', max_length=64, verbose_name='Название')),
                ('address', models.CharField(default='Без адресса', max_length=128, verbose_name='Адресс')),
                ('city', models.CharField(default='Без города', max_length=64, verbose_name='Город')),
                ('surface', models.CharField(default='Без покрытия', max_length=64, verbose_name='Покрытие')),
                ('image', models.CharField(default='Без фото', max_length=128, verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name': 'Стадион',
                'verbose_name_plural': 'Стадионы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=64, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Код команды')),
                ('logo_url', models.CharField(default='Без логотипа', max_length=64, verbose_name='Ссылка на логотип команды')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
                ('league', models.ManyToManyField(to='core.League', verbose_name='Лига')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Сезон')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue', verbose_name='Стадион')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Сезон'),
        ),
    ]
