# Generated by Django 4.2.9 on 2024-01-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_comment', models.CharField(blank=True, max_length=32, null=True, verbose_name='Комментарий победителю')),
                ('under_over', models.CharField(blank=True, max_length=32, null=True, verbose_name='ТБ/ТМ')),
                ('goals_home', models.FloatField(blank=True, null=True, verbose_name='Тотал Д')),
                ('goals_away', models.FloatField(blank=True, null=True, verbose_name='Тотал Г')),
                ('advice', models.CharField(blank=True, max_length=128, null=True, verbose_name='Предикт')),
                ('percent_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Шанс домашней')),
                ('percent_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Шанс гостевой')),
                ('percent_draw', models.CharField(blank=True, max_length=10, null=True, verbose_name='Шанс ничьи')),
                ('last_home_form', models.CharField(blank=True, max_length=10, null=True, verbose_name='Форма 5 дома')),
                ('last_away_form', models.CharField(blank=True, max_length=10, null=True, verbose_name='Форма 5 гости')),
                ('last_home_att', models.CharField(blank=True, max_length=10, null=True, verbose_name='Атака 5 дома')),
                ('last_away_att', models.CharField(blank=True, max_length=10, null=True, verbose_name='Атака 5 гости')),
                ('last_home_def', models.CharField(blank=True, max_length=10, null=True, verbose_name='Защита 5 дома')),
                ('last_away_def', models.CharField(blank=True, max_length=10, null=True, verbose_name='Защита 5 гости')),
                ('com_form_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Форма бар дома')),
                ('com_form_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Форма бар гости')),
                ('com_att_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Атака бар дома')),
                ('com_att_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Атака бар гости')),
                ('com_def_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Защита бар дома')),
                ('com_def_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Зашита бар гости')),
                ('com_distr_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Паусон бар дом')),
                ('com_distr_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Паусон бар гости')),
                ('com_h2h_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='h2h бар дом')),
                ('com_h2h_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='h2h бар гости')),
                ('com_goals_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Голы бар дома')),
                ('com_goals_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Голы бар гости')),
                ('com_total_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Общее бар дома')),
                ('com_total_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Общее бар гости')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fixture', verbose_name='Матч')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Предсказание матча',
                'verbose_name_plural': 'Предсказания матчей',
            },
        ),
    ]
