# Generated by Django 3.2.16 on 2023-12-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venue_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('form', models.CharField(default='', max_length=64, verbose_name='Форма')),
                ('played', models.PositiveIntegerField(default=0, verbose_name='Всего игр')),
                ('win', models.PositiveIntegerField(default=0, verbose_name='Победа')),
                ('draw', models.PositiveIntegerField(default=0, verbose_name='Ничья')),
                ('lose', models.PositiveIntegerField(default=0, verbose_name='Поражение')),
                ('goal_for', models.PositiveIntegerField(default=0, verbose_name='Забитых мячей')),
                ('goal_against', models.PositiveIntegerField(default=0, verbose_name='Пропущенных мячей')),
                ('played_home', models.PositiveIntegerField(default=0, verbose_name='Всего игр дома')),
                ('win_home', models.PositiveIntegerField(default=0, verbose_name='Победа дома')),
                ('draw_home', models.PositiveIntegerField(default=0, verbose_name='Ничья дома')),
                ('lose_home', models.PositiveIntegerField(default=0, verbose_name='Поражение дома')),
                ('goal_for_home', models.PositiveIntegerField(default=0, verbose_name='Забитых мячей дома')),
                ('goal_against_home', models.PositiveIntegerField(default=0, verbose_name='Пропущенных мячей дома')),
                ('played_away', models.PositiveIntegerField(default=0, verbose_name='Всего игр в гостях')),
                ('win_away', models.PositiveIntegerField(default=0, verbose_name='Победа в гостях')),
                ('draw_away', models.PositiveIntegerField(default=0, verbose_name='Ничья в гостях')),
                ('lose_away', models.PositiveIntegerField(default=0, verbose_name='Поражение в гостях')),
                ('goal_for_away', models.PositiveIntegerField(default=0, verbose_name='Забитых мячей в гостях')),
                ('goal_against_away', models.PositiveIntegerField(default=0, verbose_name='Пропущенных мячей в гостях')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league', verbose_name='Лига')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
            },
        ),
    ]
