# Generated by Django 3.2.16 on 2023-12-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaguetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Полное имя')),
                ('first_name', models.CharField(default='', max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=32, verbose_name='Фамилия')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('birthday', models.CharField(default='', max_length=32, verbose_name='День рождения')),
                ('nationality', models.CharField(default='', max_length=32, verbose_name='Национальность')),
                ('height', models.IntegerField(default=0, verbose_name='Рост')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('photo', models.CharField(default='', max_length=32, verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearences', models.IntegerField(blank=True, null=True, verbose_name='Количество появлений на поле')),
                ('lineups', models.IntegerField(blank=True, null=True, verbose_name='Количество появлений в стартовом составе')),
                ('minutes', models.IntegerField(blank=True, null=True, verbose_name='Количество минут на поле')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер игрока')),
                ('position', models.CharField(blank=True, max_length=32, null=True, verbose_name='Позиция игрока')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг игрока')),
                ('sub_in', models.IntegerField(blank=True, null=True, verbose_name='Выходов на замену')),
                ('sub_out', models.IntegerField(blank=True, null=True, verbose_name='Был заменён')),
                ('sub_bench', models.IntegerField(blank=True, null=True, verbose_name='На скамейке')),
                ('shots_total', models.IntegerField(blank=True, null=True, verbose_name='Ударов')),
                ('shots_on', models.IntegerField(blank=True, null=True, verbose_name='Ударов в створ')),
                ('goals_total', models.IntegerField(blank=True, null=True, verbose_name='Голов')),
                ('goals_assists', models.IntegerField(blank=True, null=True, verbose_name='Голевых передач')),
                ('goals_conceded', models.IntegerField(blank=True, null=True, verbose_name='Пропущенных голов')),
                ('goals_saves', models.IntegerField(blank=True, null=True, verbose_name='Сэйвов')),
                ('passes_total', models.IntegerField(blank=True, null=True, verbose_name='Передач')),
                ('passes_key', models.IntegerField(blank=True, null=True, verbose_name='Ключевых передач')),
                ('passes_accuracy', models.FloatField(blank=True, null=True, verbose_name='Процент точных передач')),
                ('tackles_total', models.IntegerField(blank=True, null=True, verbose_name='Количество отборов')),
                ('tackles_blocks', models.IntegerField(blank=True, null=True, verbose_name='Блокированных мячей')),
                ('tackles_interception', models.IntegerField(blank=True, null=True, verbose_name='Количество перехватов')),
                ('duels_total', models.IntegerField(blank=True, null=True, verbose_name='Количество единоборств')),
                ('duels_won', models.IntegerField(blank=True, null=True, verbose_name='Удачных единоборств')),
                ('dribbles_attempts', models.IntegerField(blank=True, null=True, verbose_name='Попыток дриблинга')),
                ('dribbles_success', models.IntegerField(blank=True, null=True, verbose_name='Успешных дриблингов')),
                ('dribbles_past', models.IntegerField(blank=True, null=True, verbose_name='Игроков обыгранных в дриблинге')),
                ('fouls_drawn', models.IntegerField(blank=True, null=True, verbose_name='Заработанных фолов')),
                ('fouls_committed', models.IntegerField(blank=True, null=True, verbose_name='Совершённых фолов')),
                ('cards_yellow', models.IntegerField(blank=True, null=True, verbose_name='Жёлтых карточек')),
                ('cards_yellow_red', models.IntegerField(blank=True, null=True, verbose_name='Двойных жёлтых карточек')),
                ('cards_red', models.IntegerField(blank=True, null=True, verbose_name='Красных карточек')),
                ('penalty_won', models.IntegerField(blank=True, null=True, verbose_name='Заработанных пенальти')),
                ('penalty_committed', models.IntegerField(blank=True, null=True, verbose_name='Нарушений в штрафной')),
                ('penalty_scored', models.IntegerField(blank=True, null=True, verbose_name='Забитых пенальти')),
                ('penalty_missed', models.IntegerField(blank=True, null=True, verbose_name='Не забитых пенальти')),
                ('penalty_saved', models.IntegerField(blank=True, null=True, verbose_name='Отбитых пенальти')),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.league', verbose_name='Лига')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.player', verbose_name='Игрок')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистики игроков',
            },
        ),
    ]
