# Generated by Django 3.2.16 on 2023-12-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_playerstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='season',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Сезон'),
        ),
    ]
