# Generated by Django 3.2.16 on 2023-12-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playerstatistic_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда'),
        ),
    ]
