# Generated by Django 3.2.16 on 2023-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231218_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(default='', max_length=32, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(default='', max_length=32, verbose_name='Вес'),
        ),
    ]
