# Generated by Django 3.2.16 on 2023-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231218_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.CharField(default='', max_length=128, verbose_name='Ссылка на фото'),
        ),
    ]
