# Generated by Django 3.2.16 on 2023-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Вес'),
        ),
    ]
