# Generated by Django 3.2.16 on 2023-12-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231218_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без имени', max_length=32, verbose_name='Полное имя')),
                ('first_name', models.CharField(default='Без имени', max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(default='Без имени', max_length=32, verbose_name='Фамилия')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('birthday', models.CharField(default='dd-mm-yyyy', max_length=32, verbose_name='День рождения')),
                ('nationality', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Национальность')),
                ('height', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Рост')),
                ('weight', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Вес')),
                ('photo', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Ссылка на фото')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
