# Generated by Django 3.2.16 on 2024-01-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(default='', max_length=50, verbose_name='Форма')),
                ('goal_for_015_total', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('goal_for_015_percentage', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('goal_for_1630_total', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('goal_for_1630_percentage', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('goal_for_3145_total', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('goal_for_3145_percentage', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('goal_for_4660_total', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('goal_for_4660_percentage', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('goal_for_6175_total', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('goal_for_6175_percentage', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('goal_for_7690_total', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('goal_for_7690_percentage', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('goal_against_015_total', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('goal_against_015_percentage', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('goal_against_1630_total', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('goal_against_1630_percentage', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('goal_against_3145_total', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('goal_against_3145_percentage', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('goal_against_4660_total', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('goal_against_4660_percentage', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('goal_against_6175_total', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('goal_against_6175_percentage', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('goal_against_7690_total', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('goal_against_7690_percentage', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('yellow_015_total', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('yellow_015_percentage', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('yellow_1630_total', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('yellow_1630_percentage', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('yellow_3145_total', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('yellow_3145_percentage', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('yellow_4660_total', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('yellow_4660_percentage', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('yellow_6175_total', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('yellow_6175_percentage', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('yellow_7690_total', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('yellow_7690_percentage', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('red_015_total', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('red_015_percentage', models.IntegerField(default=0, verbose_name='Голов с 0 по 15 минуты')),
                ('red_1630_total', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('red_1630_percentage', models.IntegerField(default=0, verbose_name='Голов с 16 по 30 минуты')),
                ('red_3145_total', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('red_3145_percentage', models.IntegerField(default=0, verbose_name='Голов с 31 по 45 минуты')),
                ('red_4660_total', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('red_4660_percentage', models.IntegerField(default=0, verbose_name='Голов с 46 по 60 минуты')),
                ('red_6175_total', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('red_6175_percentage', models.IntegerField(default=0, verbose_name='Голов с 61 по 75 минуты')),
                ('red_7690_total', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('red_7690_percentage', models.IntegerField(default=0, verbose_name='Голов с 76 по 90 минуты')),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.league', verbose_name='Лига')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика команды',
                'verbose_name_plural': 'Статистики команд',
            },
        ),
    ]
