# Generated by Django 3.2.16 on 2024-01-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teamstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatistic',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Сезон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_015_percentage',
            field=models.IntegerField(default=0, verbose_name='Красных с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_015_total',
            field=models.IntegerField(default=0, verbose_name='Красных с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_1630_percentage',
            field=models.IntegerField(default=0, verbose_name='Красных с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_1630_total',
            field=models.IntegerField(default=0, verbose_name='Красных с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_3145_percentage',
            field=models.IntegerField(default=0, verbose_name='Красных с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_3145_total',
            field=models.IntegerField(default=0, verbose_name='Красных с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_4660_percentage',
            field=models.IntegerField(default=0, verbose_name='Красных с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_4660_total',
            field=models.IntegerField(default=0, verbose_name='Красных с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_6175_percentage',
            field=models.IntegerField(default=0, verbose_name='Красных с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_6175_total',
            field=models.IntegerField(default=0, verbose_name='Красных с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_7690_percentage',
            field=models.IntegerField(default=0, verbose_name='Красных с 76 по 90 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_7690_total',
            field=models.IntegerField(default=0, verbose_name='Красных с 76 по 90 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_015_percentage',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_015_total',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_1630_percentage',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_1630_total',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_3145_percentage',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_3145_total',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_4660_percentage',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_4660_total',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_6175_percentage',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_6175_total',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_7690_percentage',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 76 по 90 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_7690_total',
            field=models.IntegerField(default=0, verbose_name='Жёлтых с 76 по 90 минуты'),
        ),
    ]
