# Generated by Django 3.2.16 on 2024-01-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240101_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_015_percentage',
            new_name='goal_away_015_percentage',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_015_total',
            new_name='goal_away_015_total',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_1630_percentage',
            new_name='goal_away_1630_percentage',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_1630_total',
            new_name='goal_away_1630_total',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_3145_percentage',
            new_name='goal_away_3145_percentage',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_3145_total',
            new_name='goal_away_3145_total',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_4660_percentage',
            new_name='goal_away_4660_percentage',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_4660_total',
            new_name='goal_away_4660_total',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_6175_percentage',
            new_name='goal_away_6175_percentage',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_6175_total',
            new_name='goal_away_6175_total',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_7690_percentage',
            new_name='goal_away_7690_percentage',
        ),
        migrations.RenameField(
            model_name='teamstatistic',
            old_name='goal_against_7690_total',
            new_name='goal_away_7690_total',
        ),
    ]
