# Generated by Django 3.2.16 on 2024-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240101_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_away_015_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_away_1630_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_away_3145_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_away_4660_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_away_6175_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_away_7690_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 76 по 90 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_for_015_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_for_1630_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_for_3145_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_for_4660_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_for_6175_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='goal_for_7690_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Голов с 76 по 90 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_015_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Красных с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_1630_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Красных с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_3145_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Красных с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_4660_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Красных с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_6175_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Красных с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_7690_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Красных с 76 по 90 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_015_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Жёлтых с 0 по 15 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_1630_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Жёлтых с 16 по 30 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_3145_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Жёлтых с 31 по 45 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_4660_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Жёлтых с 46 по 60 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_6175_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Жёлтых с 61 по 75 минуты'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_7690_percentage',
            field=models.CharField(default='', max_length=50, verbose_name='Жёлтых с 76 по 90 минуты'),
        ),
    ]
