# Generated by Django 3.2.16 on 2024-01-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240101_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatistic',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда'),
        ),
    ]
