# Generated by Django 3.2.16 on 2024-01-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240101_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=50, verbose_name='Дата')),
                ('status', models.CharField(default='', max_length=50, verbose_name='Статус')),
                ('goals_home', models.IntegerField(default=0, verbose_name='Голов домашней команды')),
                ('goals_away', models.IntegerField(default=0, verbose_name='Голов гостевой команды')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league', verbose_name='Лига')),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='core.team', verbose_name='Гостевая команда')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='core.team', verbose_name='Домашняя команда')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue', verbose_name='Стадион')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
