# Generated by Django 3.2.16 on 2024-01-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240102_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Сезон'),
        ),
    ]
