# Generated by Django 3.2.16 on 2024-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fixture_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(blank=True, default='Без имени', max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, default='Без имени', max_length=32, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, default='Без имени', max_length=32, null=True, verbose_name='Полное имя'),
        ),
    ]
